# Generated by Django 5.1.4 on 2025-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('idComments', models.AutoField(db_column='idComments', primary_key=True, serialize=False)),
                ('Content', models.TextField(db_column='Content')),
                ('Likes', models.IntegerField(db_column='Likes')),
                ('Dislikes', models.IntegerField(db_column='Dislikes')),
                ('Date', models.DateField(db_column='Date')),
                ('Time', models.TimeField(db_column='Time')),
                ('Title', models.TextField(db_column='Title')),
                ('Category', models.CharField(db_column='Category', max_length=45)),
                ('Comments', models.IntegerField(db_column='Comments')),
                ('Author', models.BigIntegerField(db_column='Author')),
                ('Topics_id', models.IntegerField(db_column='Topics_idTopic')),
                ('Receiver', models.TextField(db_column='Receiver')),
                ('IsAnswer', models.BooleanField(db_column='IsAnswer', null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(db_column='password', max_length=128)),
                ('Username', models.CharField(db_column='username', max_length=150)),
                ('Staff', models.BooleanField(db_column='is_staff')),
                ('Active', models.BooleanField(db_column='is_active')),
                ('Email', models.CharField(db_column='email', max_length=254)),
                ('Favorites', models.JSONField(db_column='favorites')),
            ],
            options={
                'db_table': 'api_customuser',
                'managed': False,
            },
        ),
    ]
