# Generated by Django 5.1.4 on 2025-01-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idComments', models.AutoField(db_column='idComments', primary_key=True, serialize=False)),
                ('Content', models.TextField(db_column='Content')),
                ('Likes', models.IntegerField(db_column='Likes')),
                ('Dislikes', models.IntegerField(db_column='Dislikes')),
                ('Date', models.DateField(db_column='Date')),
                ('Time', models.TimeField(db_column='Time')),
                ('Title', models.TextField(db_column='Title')),
                ('Category', models.CharField(db_column='Category', max_length=45)),
                ('Comments', models.IntegerField(db_column='Comments')),
                ('Author', models.BigIntegerField(db_column='Author')),
                ('Topics_id', models.IntegerField(db_column='Topics_idTopic')),
                ('Receiver', models.TextField(db_column='Receiver')),
                ('IsAnswer', models.BooleanField(db_column='IsAnswer', null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
