# Generated by Django 5.1.4 on 2025-01-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_alter_topic_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
