# Generated by Django 5.1.4 on 2025-01-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'managed': False},
        ),
    ]
