# Generated by Django 5.2.8 on 2026-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactive_map', '0001_add_map_name_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(db_column='idInteractive', primary_key=True, serialize=False)),
                ('data', models.JSONField(db_column='map')),
                ('map_name', models.CharField(blank=True, db_column='map_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'interactive_map',
                'managed': False,
            },
        ),
    ]
