# Generated by Django 5.1.4 on 2024-12-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_time', models.TextField(blank=True, null=True, verbose_name='Час обрізки')),
                ('cutting_description', models.TextField(blank=True, null=True, verbose_name='Опис обрізки')),
                ('cutting_treatment', models.TextField(blank=True, null=True, verbose_name='Лікування після обрізки')),
            ],
            options={
                'db_table': 'cutting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Назва хвороби')),
                ('disease_description', models.TextField(blank=True, null=True, verbose_name='Опис хвороби')),
                ('disease_treatment', models.TextField(blank=True, null=True, verbose_name='Лікування хвороби')),
            ],
            options={
                'db_table': 'diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(blank=True, max_length=45, null=True, verbose_name='Добриво')),
                ('fertilizer_type', models.CharField(blank=True, max_length=45, null=True, verbose_name='Тип добрива')),
                ('fertilizer_date', models.TextField(blank=True, null=True, verbose_name='Дата внесення добрива')),
                ('application_method', models.CharField(blank=True, max_length=45, null=True, verbose_name='Метод внесення')),
                ('quantity', models.TextField(blank=True, null=True, verbose_name='Кількість')),
                ('fertilizer_description', models.TextField(blank=True, null=True, verbose_name='Опис добрива')),
            ],
            options={
                'db_table': 'fertilizer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_time', models.TextField(blank=True, null=True, verbose_name='Час посадки')),
                ('planting_description', models.TextField(blank=True, null=True, verbose_name='Опис посадки')),
            ],
            options={
                'db_table': 'planting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сорт')),
                ('leaves', models.TextField(blank=True, null=True, verbose_name='Листя')),
                ('ground_type', models.TextField(blank=True, null=True, verbose_name='Тип ґрунту')),
                ('temperature_scope', models.TextField(blank=True, null=True, verbose_name='Температурний діапазон')),
                ('usage', models.CharField(blank=True, max_length=45, null=True, verbose_name='Використання')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image_fruit', models.TextField(blank=True, null=True, verbose_name='Зображення плоду')),
            ],
            options={
                'db_table': 'sorts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва')),
                ('family', models.CharField(blank=True, max_length=50, null=True, verbose_name='Родина')),
                ('scope_of_bloom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Період цвітіння')),
                ('ripe_time', models.CharField(blank=True, max_length=45, null=True, verbose_name='Час дозрівання')),
                ('image_tree', models.TextField(blank=True, null=True, verbose_name='Зображення дерева')),
                ('compatible', models.TextField(blank=True, null=True, verbose_name='Сумісність')),
                ('incompatible', models.TextField(blank=True, null=True, verbose_name='Несумісність')),
            ],
            options={
                'db_table': 'tree',
                'managed': False,
            },
        ),
    ]
