# Generated by Django 5.1.4 on 2025-01-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_avatar_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_token',
        ),
    ]
