# Generated by Django 5.1.4 on 2025-01-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_username_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
