# Generated by Django 5.1.4 on 2025-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_favorite_private',
            field=models.BooleanField(default=False),
        ),
    ]
