# Generated by Django 5.1.6 on 2025-03-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_customuser_is_favorite_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_map",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_map_private",
            field=models.BooleanField(default=False),
        ),
    ]
