# Generated by Django 5.1.4 on 2024-12-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('наукова_назва', models.CharField(max_length=150)),
                ('загальна_назва', models.CharField(blank=True, max_length=100, null=True)),
                ('клас', models.CharField(blank=True, max_length=50, null=True)),
                ('рід', models.CharField(blank=True, max_length=100, null=True)),
                ('родина', models.CharField(blank=True, max_length=100, null=True)),
                ('розмір', models.CharField(blank=True, max_length=100, null=True)),
                ('вага', models.CharField(blank=True, max_length=50, null=True)),
                ('тривалість_життя', models.CharField(blank=True, max_length=50, null=True)),
                ('ареал', models.TextField(blank=True, null=True)),
                ('тип_харчування', models.CharField(blank=True, max_length=50, null=True)),
                ('особливості', models.TextField(blank=True, null=True)),
                ('умови_утримання', models.TextField(blank=True, null=True)),
                ('розмноження', models.TextField(blank=True, null=True)),
                ('застосування', models.TextField(blank=True, null=True)),
                ('зображення', models.TextField(blank=True, null=True)),
                ('опис', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
