# Generated by Django 5.1.4 on 2024-12-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='animals',
        ),
    ]
