# Generated by Django 5.1.6 on 2025-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_alter_animal_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal_main",
            fields=[
                ("idAni", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(blank=True, max_length=150, null=True)),
                ("Image", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "animals_animal_main",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="animal",
            table="animals_animal",
        ),
    ]
