# Generated by Django 5.1.4 on 2025-01-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('sort_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=100)),
                ('image_url', models.TextField(blank=True, db_column='image', null=True, verbose_name='Зображення')),
            ],
            options={
                'db_table': 'animals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='id_tree',
            fields=[
                ('id', models.AutoField(db_column='idTree', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='id_vegetable',
            fields=[
                ('id', models.AutoField(db_column='idVeg', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vegetables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('sort_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('common_name', models.CharField(db_column='name', max_length=100)),
                ('image_url', models.TextField(blank=True, db_column='image', null=True, verbose_name='Зображення')),
            ],
            options={
                'db_table': 'plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('sort_id', models.AutoField(db_column='idSort', primary_key=True, serialize=False)),
                ('common_name', models.CharField(db_column='Sort', max_length=100)),
                ('image_url', models.TextField(blank=True, db_column='Image_fruit', null=True, verbose_name='Зображення плоду')),
            ],
            options={
                'db_table': 'sorts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('sort_id', models.AutoField(db_column='idSort', primary_key=True, serialize=False)),
                ('common_name', models.CharField(db_column='Name', max_length=100)),
                ('image_url', models.TextField(blank=True, db_column='Image', null=True, verbose_name='Зображення')),
            ],
            options={
                'db_table': 'sorts_veg',
                'managed': False,
            },
        ),
    ]
