# Generated by Django 5.1.4 on 2025-01-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True, db_column='Image_fruit', null=True, verbose_name='Зображення плоду')),
            ],
            options={
                'db_table': 'tree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FindVeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True, db_column='Image', null=True, verbose_name='Зображення')),
            ],
            options={
                'db_table': 'vegetables',
                'managed': False,
            },
        ),
    ]
