# Generated by Django 5.1.4 on 2025-01-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_findtree_findveg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindTree_sort',
            fields=[
                ('idTree_sort', models.IntegerField(db_column='idSort', primary_key=True, serialize=False)),
                ('common_name2', models.CharField(db_column='Sort', max_length=100)),
                ('image_url', models.TextField(blank=True, db_column='Image_fruit', null=True, verbose_name='Зображення плоду')),
                ('idTree', models.IntegerField(db_column='tree_idTree')),
            ],
            options={
                'db_table': 'sorts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FindVeg_sort',
            fields=[
                ('idVeg_sort', models.IntegerField(db_column='idSort', primary_key=True, serialize=False)),
                ('common_name2', models.CharField(db_column='Name', max_length=100)),
                ('image_url', models.TextField(blank=True, db_column='Image', null=True, verbose_name='Зображення')),
                ('idVeg', models.IntegerField(db_column='vegetables_idVeg')),
            ],
            options={
                'db_table': 'sorts_veg',
                'managed': False,
            },
        ),
    ]
