# Generated by Django 5.1.6 on 2025-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_findtree_sort_findveg_sort"),
    ]

    operations = [
        migrations.CreateModel(
            name="id_animal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idAni", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "animals_animal_main",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="animal",
            table="animals_animal",
        ),
    ]
