# Generated by Django 5.1.4 on 2025-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasesVeg',
            fields=[
                ('idDisease', models.AutoField(primary_key=True, serialize=False)),
                ('Disease_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Disease_Discription', models.TextField(blank=True, null=True)),
                ('Disease_Treatment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diseases_veg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FertilizerVeg',
            fields=[
                ('idFertilizer', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=80, null=True)),
                ('Time_Fertilizer', models.CharField(blank=True, max_length=45, null=True)),
                ('Type', models.CharField(blank=True, max_length=45, null=True)),
                ('Fertilizer_Discription', models.TextField(blank=True, db_column='Frtilizer_Discription', null=True)),
            ],
            options={
                'db_table': 'fertilizer_veg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SortsVeg',
            fields=[
                ('idSort', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=80, null=True)),
                ('Veg_Color', models.CharField(blank=True, max_length=45, null=True)),
                ('Ripe_time', models.CharField(blank=True, max_length=45, null=True)),
                ('Weight', models.CharField(blank=True, max_length=45, null=True)),
                ('Usage', models.TextField(blank=True, null=True)),
                ('Image', models.TextField(blank=True, null=True)),
                ('Discription', models.TextField(blank=True, db_column='Discription', null=True)),
            ],
            options={
                'db_table': 'sorts_veg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('idVeg', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=150, null=True)),
                ('Type', models.CharField(blank=True, max_length=45, null=True)),
                ('Protein_content', models.CharField(blank=True, max_length=45, null=True)),
                ('Fat_content', models.CharField(blank=True, db_column='Fat_сontent', max_length=45, null=True)),
                ('Carb_content', models.CharField(blank=True, max_length=45, null=True)),
                ('Vitamins', models.TextField(blank=True, null=True)),
                ('Minerals', models.TextField(blank=True, null=True)),
                ('Plant_time', models.CharField(blank=True, max_length=45, null=True)),
                ('Compatibility', models.TextField(blank=True, null=True)),
                ('Incompatibility', models.TextField(blank=True, null=True)),
                ('Image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vegetables',
                'managed': False,
            },
        ),
    ]
