# Generated by Django 5.1.4 on 2025-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.AutoField(db_column='idCutting', primary_key=True, serialize=False)),
                ('Cutting_time_From', models.CharField(max_length=5)),
                ('Cutting_time_To', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'cutting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(db_column='idFertilizer', primary_key=True, serialize=False)),
                ('Fertilizer_date_From1', models.CharField(max_length=5)),
                ('Fertilizer_date_To1', models.CharField(max_length=5)),
                ('Fertilizer_date_From2', models.CharField(max_length=5)),
                ('Fertilizer_date_To2', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'fertilizer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fertilizer_veg',
            fields=[
                ('id', models.AutoField(db_column='idFertilizer', primary_key=True, serialize=False)),
                ('Time_Fertilizer_From1', models.CharField(max_length=5)),
                ('Time_Fertilizer_To1', models.CharField(max_length=5)),
                ('Time_Fertilizer_From2', models.CharField(max_length=5)),
                ('Time_Fertilizer_To2', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'fertilizer_veg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(db_column='idPlantting', primary_key=True, serialize=False)),
                ('Plant_time_From', models.CharField(max_length=5)),
                ('Plant_time_To', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'planting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=5)),
                ('end_date', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sort_tree',
            fields=[
                ('id', models.AutoField(db_column='idSort', primary_key=True, serialize=False)),
                ('Usage', models.CharField(max_length=100)),
                ('sort', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сорт')),
            ],
            options={
                'db_table': 'sorts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sort_veg',
            fields=[
                ('id', models.AutoField(db_column='idSort', primary_key=True, serialize=False)),
                ('Ripe_time_From1', models.CharField(max_length=5)),
                ('Ripe_time_To1', models.CharField(max_length=5)),
                ('Ripe_time_From2', models.CharField(max_length=5)),
                ('Ripe_time_To2', models.CharField(max_length=5)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sorts_veg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('idTree', models.AutoField(primary_key=True, serialize=False)),
                ('Scope_of_bloom_From', models.CharField(max_length=5)),
                ('Scope_of_bloom_To', models.CharField(max_length=5)),
                ('Ripe_Time_From', models.CharField(max_length=5)),
                ('Ripe_Time_To', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veg',
            fields=[
                ('idVeg', models.AutoField(primary_key=True, serialize=False)),
                ('Plant_time_From1', models.CharField(max_length=5)),
                ('Plant_time_From2', models.CharField(db_column='Plant_time_To2', max_length=5)),
                ('Plant_time_To2', models.CharField(db_column='Plant_time_From2', max_length=5)),
                ('Plant_time_To1', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'vegetables',
                'managed': False,
            },
        ),
    ]
