# Generated by Django 5.1.4 on 2025-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_life', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.TextField()),
                ('flower_color', models.CharField(blank=True, max_length=100, null=True)),
                ('flowering_period', models.CharField(blank=True, max_length=50, null=True)),
                ('conditions_of_care', models.TextField()),
                ('growth_regions', models.CharField(blank=True, max_length=200, null=True)),
                ('soil', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('recommended_humidity', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'plants',
                'managed': False,
            },
        ),
    ]
